# Generated by Django 3.1.5 on 2021-01-15 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grocerylist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='groceries',
            name='completedate',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
